// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzBbUqpA9A2ISfQC1w3skn-xlTYjotEf0',
    appId: '1:32313479080:web:5db595856830b950a1179d',
    messagingSenderId: '32313479080',
    projectId: 'pmu-parking',
    authDomain: 'pmu-parking.firebaseapp.com',
    storageBucket: 'pmu-parking.firebasestorage.app',
    measurementId: 'G-CFY60WXGST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTUgKLKPVzkQyXkj4qkJaj9oaDh2Ggkj4',
    appId: '1:32313479080:android:305d727599d1b708a1179d',
    messagingSenderId: '32313479080',
    projectId: 'pmu-parking',
    storageBucket: 'pmu-parking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIzY_f6HJXn8XvkslqBsPleCPSimT1eZc',
    appId: '1:32313479080:ios:1a056736c340fb32a1179d',
    messagingSenderId: '32313479080',
    projectId: 'pmu-parking',
    storageBucket: 'pmu-parking.firebasestorage.app',
    iosBundleId: 'com.app.parking.pmuParking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIzY_f6HJXn8XvkslqBsPleCPSimT1eZc',
    appId: '1:32313479080:ios:1a056736c340fb32a1179d',
    messagingSenderId: '32313479080',
    projectId: 'pmu-parking',
    storageBucket: 'pmu-parking.firebasestorage.app',
    iosBundleId: 'com.app.parking.pmuParking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzBbUqpA9A2ISfQC1w3skn-xlTYjotEf0',
    appId: '1:32313479080:web:459c7f56fb878751a1179d',
    messagingSenderId: '32313479080',
    projectId: 'pmu-parking',
    authDomain: 'pmu-parking.firebaseapp.com',
    storageBucket: 'pmu-parking.firebasestorage.app',
    measurementId: 'G-CTTPN78MLF',
  );
}
